import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';

export default function TermsOfServicePage() {
  return (
    <div className="flex flex-col min-h-screen">
      <Header />
      <main className="flex-grow container mx-auto px-4 py-12">
        <Card className="max-w-3xl mx-auto">
          <CardHeader>
            <CardTitle className="text-3xl font-bold text-center">Terms of Service</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4 text-muted-foreground">
            <p><strong>Last Updated: {new Date().toLocaleDateString()}</strong></p>

            <p>Please read these Terms of Service ("Terms", "Terms of Service") carefully before using the ResumeRocket website (the "Service") operated by ResumeRocket ("us", "we", or "our").</p>
            <p>Your access to and use of the Service is conditioned upon your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who wish to access or use the Service.</p>
            <p>By accessing or using the Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you do not have permission to access the Service.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">1. Use of Service</h2>
            <p>ResumeRocket provides an AI-powered tool to help users tailor resumes and generate cover letters. You agree to use the Service only for lawful purposes and in accordance with these Terms.</p>
            <p>You are responsible for the content you provide (resume text, job descriptions) and for ensuring that it does not violate any third-party rights or applicable laws.</p>
            <p>The Service costs $1.50 per generation of a tailored resume and cover letter. This fee is subject to change.</p>
            
            <h2 className="text-xl font-semibold text-foreground pt-4">2. Intellectual Property</h2>
            <p>The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of ResumeRocket and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries.</p>
            <p>You retain all rights to the content you submit to the Service. By submitting content, you grant us a non-exclusive, worldwide, royalty-free license to use, reproduce, modify, and process such content solely for the purpose of providing the Service to you.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">3. AI Generated Content</h2>
            <p>The tailored resumes and cover letters generated by the Service are created by artificial intelligence. While we strive for accuracy and effectiveness, we do not guarantee that the generated content will be error-free, perfectly suited for every job application, or result in employment.</p>
            <p>You are responsible for reviewing and editing any content generated by the Service before using it for job applications. ResumeRocket is not liable for any outcomes related to your use of the generated content.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">4. Payments</h2>
            <p>All payments for using the Service are processed through a third-party payment processor. We do not store your full credit card information. By making a payment, you agree to the terms and conditions of our payment processor.</p>
            <p>Fees for the Service are non-refundable except as required by law or at our sole discretion.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">5. Termination</h2>
            <p>We may terminate or suspend your access to the Service immediately, without prior notice or liability, under our sole discretion, for any reason whatsoever, including but not limited to a breach of the Terms.</p>
            <p>All provisions of the Terms which by their nature should survive termination shall survive termination, including, without limitation, ownership provisions, warranty disclaimers, indemnity, and limitations of liability.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">6. Disclaimer of Warranties; Limitation of Liability</h2>
            <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis. We disclaim all warranties of any kind, whether express or implied, including, but not limited to, implied warranties of merchantability, fitness for a particular purpose, and non-infringement.</p>
            <p>In no event shall ResumeRocket, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from (i) your access to or use of or inability to access or use the Service; (ii) any conduct or content of any third party on the Service; (iii) any content obtained from the Service; and (iv) unauthorized access, use or alteration of your transmissions or content, whether based on warranty, contract, tort (including negligence) or any other legal theory, whether or not we have been informed of the possibility of such damage, and even if a remedy set forth herein is found to have failed of its essential purpose.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">7. Governing Law</h2>
            <p>These Terms shall be governed and construed in accordance with the laws of [Your Jurisdiction - e.g., State of California, United States], without regard to its conflict of law provisions.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">8. Changes to Terms</h2>
            <p>We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.</p>
            <p>By continuing to access or use our Service after any revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Service.</p>

            <h2 className="text-xl font-semibold text-foreground pt-4">9. Contact Us</h2>
            <p>If you have any questions about these Terms, please contact us at: [Your Contact Email Address or Link to Contact Form - e.g., support@resumerocket.com]</p>
          </CardContent>
        </Card>
      </main>
      <Footer />
    </div>
  );
}
